[tool.kedro]
package_name = "nhanes_pipeline"
project_name = "nhanes-health-analytics"
kedro_init_version = "1.4.0"

[project]
name = "nhanes-health-analytics"
version = "0.1.0"
description = "Kedro pipeline for NHANES longevity analysis"
readme = "README.md"
requires-python = ">=3.9"

[tool.kedro_telemetry]
project_id = "b5f4e28cfc164e3d994a0d9335df377c"
